name: Create new release binary
on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write


jobs:
  deploy:
    name: Create new release binarys
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]

    steps:
      - uses: actions/checkout@v3
      - name: Go Release Binaries
        uses: wangyoucao577/go-release-action@v1.38
        with:
          github_token: ${{ secrets.RELEASE_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          binary_name: "goworkrbx"
          extra_files: README.md LICENSE
